import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { days, weeks, resources } from './source/course.mjs';
const root = dirname(fileURLToPath(import.meta.url));
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list = (items,tag='ul') => `<${tag}>${items.map(t=>`<li>${esc(t)}</li>`).join('')}</${tag}>`;
const detail = (n,title,body,open=false) => `<details${open?' open':''}><summary><span class="seq">${n}</span>${title}</summary><div class="detail-body">${body}</div></details>`;
const renderDay = d => `<article class="day" id="day-${d.day}" data-day="${d.day}">
<header class="day-title"><h3><span class="day-number">DAY ${String(d.day).padStart(2,'0')}</span>${esc(d.title)}</h3><span class="time">约 120 分钟</span></header>
<p class="goal">${esc(d.goal)}</p><div class="lesson-grid">
${detail('01','先理解 · 20 分钟',d.learn.map(t=>`<p>${esc(t)}</p>`).join(''),d.day===1)}
${detail('02','动手做 · 80 分钟',list(d.steps,'ol')+`<div class="callout"><b>故障与边界练习</b>${esc(d.failure)}</div>`,d.day===1)}
${detail('03','验收与交付物',`<p><strong>今日交付：</strong>${esc(d.output)}</p>${d.checks.map((t,i)=>`<label class="check-row"><input type="checkbox" data-check="${i}" aria-label="Day ${d.day} 验收 ${i+1}：${esc(t)}"><span>${esc(t)}</span></label>`).join('')}`)}
${detail('04','复盘与参考答案 · 20 分钟',`<p><strong>${esc(d.question)}</strong></p><p>${esc(d.answer)}</p><div class="callout"><b>先自己回答，再核对</b>记录今天的判断、证据、未解决问题，以及下次怎样验证。</div>`)}
${detail('05','学习资料与阅读范围',d.refs.length?d.refs.map(id=>{const r=resources[id];return `<div class="resource"><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a><p>${esc(r.guide)}</p></div>`;}).join(''):'<p>回到本周自己的代码、操作记录和验证结果。本日以整理证据与实际复测为主。</p>')}
</div><label class="notes" for="note-${d.day}">练习证据与复盘 <span class="notes-hint">自动保存在当前浏览器</span><textarea id="note-${d.day}" maxlength="20000" placeholder="实际完成了什么？证据在哪里？哪些情况还没有通过？"></textarea></label>
<div class="day-actions"><button class="completion" type="button" aria-pressed="false" disabled>标记今日已验收</button><span class="gate-hint">完成 3 项验收，并记录证据后可标记。</span></div></article>`;
const nav = weeks.map(w=>`<section class="nav-group"><h2>第 ${w.id} 周 · ${w.title}</h2>${days.filter(d=>Math.ceil(d.day/5)===w.id).map(d=>`<a href="#day-${d.day}" data-nav="${d.day}"><span>${String(d.day).padStart(2,'0')}</span><span>${esc(d.title)}</span></a>`).join('')}</section>`).join('');
const body = weeks.filter(w=>days.some(d=>Math.ceil(d.day/5)===w.id)).map(w=>`<section class="week" id="week-${w.id}"><header class="week-head"><p class="eyebrow">WEEK ${String(w.id).padStart(2,'0')} · DAY ${(w.id-1)*5+1}–${w.id*5}</p><h2>${w.title}</h2><p>${w.subtitle}</p></header><div class="week-gate"><strong>本周验收</strong>${w.gate}</div>${days.filter(d=>Math.ceil(d.day/5)===w.id).map(renderDay).join('')}</section>`).join('');
const [css,progress,app] = await Promise.all(['styles.css','progress.mjs','app.js'].map(name=>readFile(resolve(root,'source',name),'utf8')));
const script = `{\n${progress.replaceAll('export ','')}\n${app}\n}`;
const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="description" content="围绕 Job Agent 的 AI FDE 三周实战学习：系统修改与排错、模型效果评测、用户试用交付。15 个练习日，支持本地进度与笔记导出。"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; connect-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>AI FDE 三周实战 · 学习工作台</title><style>${css}</style></head>
<body data-theme="light"><a class="skip" href="#content">跳到学习内容</a><div class="reading-line" aria-hidden="true"></div><div class="layout">
<button class="scrim" id="scrim" aria-label="关闭目录" tabindex="-1"></button>
<aside class="sidebar" id="sidebar"><div class="brand"><i>15</i><span>AI FDE<br>学习工作台</span></div><button id="menu-close" class="close-menu" aria-label="关闭目录">×</button><p class="muted">三周实战 · 从项目到交付</p><div class="course-links"><a class="active" href="#content" aria-current="page">三周实战训练</a><a href="https://mu-xin1.github.io/intelligence-agent-os-learning/#/fde-90">90 天系统训练 ↗</a><a href="https://mu-xin1.github.io/intelligence-agent-os-learning/#/fde-14">14 天面试冲刺 ↗</a></div><div class="side-progress"><div class="progress-caption"><span>已验收的练习日</span><strong id="progress-value">0 / 15</strong></div><progress id="progress-bar" max="15" value="0" aria-label="课程验收进度"></progress></div><nav aria-label="每日课程目录">${nav}</nav><p class="sidebar-foot muted">进度与笔记只保存在当前浏览器。<br>换设备前，导出进度备份。</p></aside>
<main class="main"><header class="toolbar" id="toolbar"><button id="menu-open" class="mobile-menu" aria-label="打开目录" aria-controls="sidebar" aria-expanded="false">目录</button><label class="search"><input id="search" type="search" aria-label="搜索每日课程" placeholder="搜索课程、故障或交付物…"></label><div class="tools"><button id="expand-all">全部展开</button><button id="theme">深色</button><button id="export-json">导出进度</button><button id="export-md">导出笔记</button><button id="import-trigger">导入</button><input id="import-file" type="file" accept="application/json,.json" hidden><button id="print">打印</button><a href="./AI-FDE-三周实战-离线版.html" download>离线版 ↓</a></div></header>
<div class="warning" id="storage-warning" hidden>当前浏览器无法稳定保存记录，请在关闭前导出进度。</div><div class="status" id="status" role="status" aria-live="polite" hidden></div><div class="content" id="content"><section class="intro"><p class="eyebrow">JOB AGENT · PROJECT PRACTICE</p><h1>把项目练成可交付的能力</h1><p>沿着已有项目，完成一次系统修改、一轮模型评测和一次用户试用。每天留下可复查的结果，再进入下一步。</p><div class="plan-row"><span class="pill">3 周 · 15 个练习日</span><span class="pill">每天约 2 小时</span><span class="pill">约 30 小时起步</span><a id="continue" class="continue" href="#day-1">继续 Day 01 →</a></div></section>
<div class="week-strip">${weeks.map(w=>`<a href="#week-${w.id}"><small>第 ${w.id} 周</small><b>${w.title} →</b></a>`).join('')}</div><p class="routine">每日节奏：理解 20 分钟 → 操作 80 分钟 → 复盘 20 分钟。每周安排 5 个练习日；未通过验收就继续练。可使用 AI 辅助，你负责判断、核查与解释。</p><noscript><p class="warning">课程正文可以直接阅读；启用 JavaScript 后可搜索、记录进度和导出笔记。</p></noscript><p id="search-count" role="status" aria-live="polite"></p><p class="empty" id="empty" hidden>没有找到匹配的课程，换个关键词试试。</p>${body}
<section class="wrap-up" id="review"><p class="eyebrow">FINAL REVIEW</p><h2>用三份交付物检查这一轮收获</h2><ol><li>系统掌控：一次需求修改、对应验证和故障定位记录。</li><li>AI 评测：案例集、比较结果、失败样本与改进依据。</li><li>用户交付：需求记录、使用说明、观察结果与复测记录。</li></ol><p>三周是第一轮训练安排。个人试用与小样本评测提供初步证据；企业系统集成、权限管理和持续运维，需要在后续真实项目中继续积累。</p><p>项目迁移：Pupil 可复盘跨设备故障与测试流程；华丰案例可练习需求范围、规则与人工处理边界。模拟练习如实标注为模拟，不作为客户上线成果。</p></section><footer><span>AI FDE · 三周实战学习 · 2026.09</span><a href="#content">返回顶部 ↑</a></footer></div></main></div><script>${script.replaceAll('</script','<\\/script')}</script></body></html>`;
await Promise.all(['index.html','AI-FDE-三周实战-离线版.html'].map(name=>writeFile(resolve(root,name),html)));
console.log(`Built ${days.length} lessons into standalone HTML (${Buffer.byteLength(html)} bytes).`);
